version: "3.9"
services:

    nginx:
        image: nginx:1.18
        container_name: "nginx"
        volumes:
            - ./nginx:/etc/nginx
        ports:
            - "80:80"
        networks: 
            - apinetwork


    pg_seller:
        image: postgres
        env_file: .env
        ports: 
            - "5440:5432"
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]
            timeout: 3s
            interval: 5s
            retries: 3
                
    django_seller:
        build: .
        env_file: .env
        volumes:
            - ./:/var/www
        ports: 
            - "8000:8000"
        depends_on:
            pg_seller:
                condition: service_healthy
        command: sh -f entrypoint.sh
        
networks: 
    apinetwork:
            driver: bridge