# Generated by Django 3.2.4 on 2021-06-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('marketplace', models.CharField(max_length=50, verbose_name='marketplace')),
            ],
        ),
    ]
